### ISSUE TITLE
Issues in default theme

### ISSUE THREAD

**Issue by dhineshkr** [quokkaproject/quokka#142]
I created a quokka project with the steps with quick start quide from https://github.com/pythonhub/quokka. Things are fine but the admin link http://127.0.0.1:5000/admin/
gives error like below.

Traceback (most recent call last):
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask_security/decorators.py", line 205, in wrapper
    return f(_args, *_kwargs)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask_security/views.py", line 88, in login
    **_ctx('login'))
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka/quokka/templates/security/login_user.html", line 1, in top-level template code
    {% extends theme("base.html") %}
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/quokka_themes/__init__.py", line 67, in global_theme_template
    theme = active_theme(ctx)
  File "/Users/dhineshkumar/Dhinesh/Dev/python/flask/quokka-env/lib/python2.7/site-packages/quokka_themes/**init**.py", line 62, in active_theme
    raise RuntimeError("Could not find the active theme")
RuntimeError: Could not find the active theme

**Comment by rochacbruno** [comment]
What O.S and Python version?

**Comment by dhineshkr** [comment]
Mac OS X 10.8.5 and Python 2.7

**Comment by dhineshkr** [comment]
pip freeze
#########
Babel==1.3
Flask==0.10.1
Flask-Admin==1.0.7
Flask-BabelEx==0.9.1
Flask-Cache==0.12
Flask-Collect==0.2.2
Flask-Gravatar==0.4.1
Flask-HTMLBuilder==0.4
Flask-Login==0.2.6
Flask-Mail==0.9.0
Flask-Mistune==0.1.1
Flask-OAuthlib==0.4.3
Flask-Principal==0.4.0
Flask-Script==0.6.7
Flask-Security==1.7.1
Flask-WTF==0.9.5
Jinja2==2.7.2
MarkupSafe==0.19
Quokka-Themes==0.1.2
Unidecode==0.04.14
WTForms==1.0.5
Werkzeug==0.9.4
awesome-slugify==1.2.2
blinker==1.3
dealer==1.1.0
flask-mongoengine==0.7.0
itsdangerous==0.23
mistune==0.2.0
mongoengine==0.8.7
oauthlib==0.6.1
passlib==1.6.2
pymongo==2.6.3
pytz==2014.1.1
simplejson==3.3.3
speaklater==1.3
wsgiref==0.1.2

**Comment by dhineshkr** [comment]
Duplicate of issue - "Cant access to admin page #90" Reinstall of Flask-Security had solved this issue.

**Comment by DiegoYungh** [comment]
Nice :+1:
