### ISSUE TITLE
Syntax error in models.py

### ISSUE THREAD

**Issue by vwbusguy** [quokkaproject/quokka#165]
From initial install, running first test.

```
(env)[sawilliams@webapps-dev quokka]$ python runtests.py 
EEEEEEE............
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
SyntaxError: invalid syntax (models.py, line 298)
-------------------- >> begin captured logging << --------------------
passlib.utils.compat: DEBUG: loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x7feb83111ad0>
passlib.utils.compat: DEBUG: loaded lazy attr 'NativeStringIO': <built-in function StringIO>
passlib.utils.compat: DEBUG: loaded lazy attr 'BytesIO': <built-in function StringIO>
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/core/tests/__init__.py", line 5, in <module>
    from quokka.core.admin import create_admin
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/ext/__init__.py", line 9, in <module>
    from quokka.core.admin import configure_admin
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/modules/accounts/tests/test_model.py", line 4, in <module>
    from quokka.core.tests import BaseTestCase
  File "/git/webapps-flaskdoc/quokka/quokka/core/tests/__init__.py", line 5, in <module>
    from quokka.core.admin import create_admin
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/modules/comments/__init__.py", line 4, in <module>
    from .views import CommentView
  File "/git/webapps-flaskdoc/quokka/quokka/modules/comments/views.py", line 9, in <module>
    from .models import Comment
  File "/git/webapps-flaskdoc/quokka/quokka/modules/comments/models.py", line 4, in <module>
    from quokka.core.models import Publishable
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/modules/posts/tests/test_model.py", line 2, in <module>
    from quokka.core.tests import BaseTestCase
  File "/git/webapps-flaskdoc/quokka/quokka/core/tests/__init__.py", line 5, in <module>
    from quokka.core.admin import create_admin
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (models.py, line 298))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/git/webapps-flaskdoc/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/webapps-flaskdoc/quokka/quokka/tests/test_basic.py", line 4, in <module>
    from quokka.core.admin import create_admin
  File "/git/webapps-flaskdoc/quokka/quokka/core/admin/__init__.py", line 9, in <module>
    from ..models import (Link, Config, SubContentPurpose, ChannelType,
  File "/git/webapps-flaskdoc/quokka/quokka/core/models.py", line 298
    for c in self.get_ancestors(channel_type__ne=None)
      ^
SyntaxError: invalid syntax

Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
quokka                              47     31    34%   17-20, 28-51, 55, 59-73
quokka.contrib                       0      0   100%   
quokka.core                          1      0   100%   
quokka.core.app                      3      0   100%   
quokka.core.cache                    2      0   100%   
quokka.core.db                       4      0   100%   
quokka.core.fields                  87     67    23%   12, 16, 20-22, 26-30, 34-37, 41-46, 50-62, 66-73, 77-80, 84-96, 100-102, 106-112, 117-118, 123-125
quokka.core.templates               10      7    30%   8-16
quokka.modules                       0      0   100%   
quokka.modules.accounts              2      0   100%   
quokka.modules.accounts.models      65     21    68%   16, 22, 47-53, 57-60, 63-65, 71-72, 83, 86, 90, 107
quokka.modules.media                 2      0   100%   
quokka.modules.posts                 2      0   100%   
quokka.settings                     49      0   100%   
quokka.utils                        19     13    32%   10-11, 17-29
quokka.utils.text                   20      0   100%   
--------------------------------------------------------------
TOTAL                              313    139    56%   
----------------------------------------------------------------------
Ran 19 tests in 0.593s

FAILED (errors=7)
```

Environment:
- CentOS 6.5
- Kernel: 2.6.32-358.6.1.el6.x86_64
- Python 2.6.6
- Virtualenv

Using virtualenv as normal user.  As a note, the same setup works for Flask and Django generally.  I currently have Mezzanine running on the same instance.

**Comment by ellisonleao** [comment]
I will take a look at it! :smile:

**Comment by ellisonleao** [comment]
Hey @vwbusguy , this is a python version issue, i will update the code to be python 2.6 compatible, but if you update to python 2.7 the problem is resolved.

**Comment by vwbusguy** [comment]
Thanks for the update, I'll try it out with py27.

Scott
