### ISSUE TITLE
python manage.py populate gave me ImportError: No module named oauthlib.oauth1 

### ISSUE THREAD

**Issue by dvdme** [quokkaproject/quokka#184]
```
D:\Projects\quokka>python manage.py populate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from quokka.ext.blueprints import load_blueprint_commands
  File "D:\Projects\quokka\quokka\ext\__init__.py", line 13, in <module>
    from . import (generic, babel, blueprints, error_handlers, context_processors,
  File "D:\Projects\quokka\quokka\ext\oauthlib.py", line 4, in <module>
    from flask.ext.oauthlib.client import OAuth
  File "C:\Python27\lib\site-packages\flask\exthook.py", line 81, in load_module

    reraise(exc_type, exc_value, tb.tb_next)
  File "C:\Python27\lib\site-packages\flask_oauthlib\client.py", line 12, in <module>
    import oauthlib.oauth1
ImportError: No module named oauthlib.oauth1
```

Running `pip install oauthlib` solved the problem.
Looking at `requirements.txt` I noticed that that module wasn't here. But I suppose it should be installed with Flask-OAuthlib.

This was with Python 2.7 at Windows 8.1 64

**Comment by alexandre** [comment]
@dvdme ,

If flask-ouauthlib uses oauthlib, it is/should be a requirement of flask-ouathlib, take a look:

``` python
# I executed pip install flask-ouathlib before
(flask-oauth)ubb3rs17h@lastzion ~/Devel/flask-oauth $ pip freeze|grep oauthlib
oauthlib==0.7.2
```

On your terminal, try to use the parameter --upgrade:

```
pip install --upgrade -r requirements.txt
```

P.S: I'm not a Windows user, but I think is a valid test.

[ ]'s (hugs)
