### ISSUE TITLE
mongoengine.connection.ConnectionError: Cannot connect to database default : False is not a read preference.

### ISSUE THREAD

**Issue by qsLI** [quokkaproject/quokka#186]
when I type python manage.py populate,I got some exception
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    app = create_app()
  File "D:\code\python\flask\quokka-master\quokka__init__.py", line 49, in create_app
    configure_extensions(app, admin_instance or admin)
  File "D:\code\python\flask\quokka-master\quokka\ext__init__.py", line 30, in configure_extensions
    db.init_app(app)
  File "C:\Python27\lib\site-packages\flask_mongoengine-0.7.1-py2.7.egg\flask_mongoengine__init__.py", line 66, in init_app
    self.connection = mongoengine.connect(**conn_settings)
  File "build\bdist.win32\egg\mongoengine\connection.py", line 164, in connect
  File "build\bdist.win32\egg\mongoengine\connection.py", line 126, in get_connection
mongoengine.connection.ConnectionError: Cannot connect to database default :
False is not a read preference.

**Comment by rochacbruno** [comment]
Did you configured your database in settings file? is mongoDb running?

**Comment by qsLI** [comment]
I configured. I solved it. It was because pymongo version too high.

**Comment by ez47** [comment]
Can you explain for other people how you fixed it? Am running into this aswell.

**Comment by ellisonleao** [comment]
@ez47 did you try to configure the local_settings.py file for the mongodb database?

https://github.com/quokkaproject/quokka/wiki/installation#configure-your-database-settings

**Comment by ez47** [comment]
yes nvm, i found out what was wrong. I needed to pip install pymongo==2.7.1 to downgrade from pymongo 3.xx
