### ISSUE TITLE
Upgrade Flask-Admin

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#201]
https://github.com/flask-admin/flask-admin changed a lot, now there is the need to adjust Quokka templaring and Quokka-themes to work with the new admin

**Comment by rochacbruno** [comment]
Now it will work if admin installed from pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip

```
pip install pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip
```

**Comment by QiXuanWang** [comment]
pip install pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip
Is it a typo? I removed  1 " pip install" among that.

After I upgrade Flask-admin to 1.0.8 and updated git repo for quokka, when I start quokka with my old command it won't work, reports:
py manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from quokka.ext.blueprints import load_blueprint_commands
  File "/remote/tools/Git/quokka/quokka/ext/__init__.py", line 9, in <module>
    from quokka.core.admin import configure_admin
  File "/remote/tools/Git/quokka/quokka/core/admin/__init__.py", line 12, in <module>
    from .models import ModelAdmin, FileAdmin, BaseIndexView
  File "/remote/tools/Git/quokka/quokka/core/admin/models.py", line 6, in <module>
    from flask.ext.admin.contrib.mongoengine import ModelView
    from quokka.core.admin import configure_admin
  File "/remote/tools/Git/quokka/quokka/core/admin/__init__.py", line 12, in <module>
    from .models import ModelAdmin, FileAdmin, BaseIndexView
  File "/remote/tools/Git/quokka/quokka/core/admin/models.py", line 6, in <module>
    from flask.ext.admin.contrib.mongoengine import ModelView
  File "/remote/tools/Python-2.7.3/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/remote/tools/Python-2.7.3/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/__init__.py", line 6, in <module>
    from .view import ModelView
  File "/remote/tools/Python-2.7.3/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 17, in <module>
    from .form import get_form, CustomModelConverter
  File "/remote/tools/Python-2.7.3/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/form.py", line 13, in <module>
    from .fields import ModelFormField, MongoFileField, MongoImageField
  File "/remote/tools/Python-2.7.3/lib/python2.7/site-packages/flask_admin/contrib/mongoengine/fields.py", line 4, in <module>
    from wtforms.fields.core import _unset_value
ImportError: cannot import name _unset_value

**Comment by QiXuanWang** [comment]
You need to update with latest repo version 1.0.8 will report an error for me:
flask_admin/contrib/mongoengine/fields.py", line 4, in <module>
    from wtforms.fields.core import _unset_value
ImportError: cannot import name _unset_value
It's changed to unset_value in repo but not 1.0.8. 

But, this change won't resolve #189 and #199 ?

**Comment by QiXuanWang** [comment]
what's the correct step to doing update? I tried pip install Flask-Admin and it won't work. 
Then I tried to redo "pip install -r requirements.txt". Though there is a build failure for lxml, I make it works for post delete and other stuffs fixed.

**Comment by rochacbruno** [comment]
Working on #290

![home quokka admin](https://cloud.githubusercontent.com/assets/458654/9420623/049b81f8-483e-11e5-8f90-f558adbfc303.png)
