### ISSUE TITLE
I have problems when installation

### ISSUE THREAD

**Issue by netqyq** [quokkaproject/quokka#212]
(venv)[root@ctos quokka]# python manage.py populate
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    app = create_app()
  File "/root/quokka/quokka/**init**.py", line 49, in create_app
    configure_extensions(app, admin_instance or admin)
  File "/root/quokka/quokka/ext/**init**.py", line 30, in configure_extensions
    db.init_app(app)
  File "/root/quokka/venv/lib/python2.7/site-packages/flask_mongoengine/**init**.py", line 60, in init_app
    conn_settings = dict([(k.lower(), v) for k, v in conn_settings.items() if v])
AttributeError: 'set' object has no attribute 'items'

**Comment by rochacbruno** [comment]
Can you tell me what is your Python version?

**Comment by netqyq** [comment]
(venv)[root@ctos quokka]# python -V
Python 2.7.9

**Comment by netqyq** [comment]
I have installed a mongodb, and started, that crate a test db,  no other further settings, is that mongodb's configuration reason?

**Comment by rochacbruno** [comment]
The error is in flask_mongoengine package

``` python
File "/root/quokka/venv/lib/python2.7/site-packages/flask_mongoengine/init.py", line 60, in init_app
conn_settings = dict([(k.lower(), v) for k, v in conn_settings.items() if v])
AttributeError: 'set' object has no attribute 'items'
```

Have you changed something in your settings file?

**Comment by netqyq** [comment]
it works ! that's my fault! my config file wrong , Thank you !

# local_setting.py should be:

MONGODB_SETTINGS = {'DB': 'test'}
DEBUG = True
