### ISSUE TITLE
I have problems when installation for mongoDB auth

### ISSUE THREAD

**Issue by xh84** [quokkaproject/quokka#223]
win7 32bit with python2.7.9 

i install mongo 3.0.4 and set a new database named "quokka_db", and then 

db.createUser(
    {
      user: "root",
      pwd: "root",
      roles: [
         { role: "readWrite", db: "quokka_db" }
      ]
    }
)
set a 'root' user

in local_setting.py, i set 

MONGODB_SETTINGS = {'DB': "quokka_db",
                     'USERNAME': 'root',
                     'PASSWORD': 'root',
                     }

but i get the errors:

(env) E:\python\quokka-cms\quokka-master>python manage.py createsuperuser

Error importing flask-weasyprint!
PDF support is temporarily disabled.
Manual dependencies may need to be installed.
See,
    `http://weasyprint.org/docs/install/#by-platform`_
    `https://github.com/Kozea/WeasyPrint/issues/79`_

   No module named flask_weasyprint
   No handlers could be found for logger "DEALER"
   Loading fixtures
   Traceback (most recent call last):
     File "manage.py", line 12, in <module>
      app = create_app()
     File "E:\python\quokka-cms\quokka-master\quokka__init__.py", line 49, in crea
   te_app
      configure_extensions(app, admin_instance or admin)
     File "E:\python\quokka-cms\quokka-master\quokka\ext__init__.py", line 31, in
   configure_extensions
      fixtures.configure(app, db)
     File "E:\python\quokka-cms\quokka-master\quokka\ext\fixtures.py", line 17, in
   configure
      populate.create_configs()
     File "E:\python\quokka-cms\quokka-master\quokka\utils\populate.py", line 89, i
   n create_configs
      self.create_config(config)
     File "E:\python\quokka-cms\quokka-master\quokka\utils\populate.py", line 72, i
   n create_config
      return Config.objects.create(**data)
     File "E:\python\quokka-cms\env\lib\site-packages\mongoengine\queryset\manager.
   py", line 37, in **get**
      queryset = queryset_class(owner, owner._get_collection())
     File "E:\python\quokka-cms\env\lib\site-packages\mongoengine\document.py", lin
   e 168, in _get_collection
      db = cls._get_db()
     File "E:\python\quokka-cms\env\lib\site-packages\mongoengine\document.py", lin
   e 162, in _get_db
      return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
     File "E:\python\quokka-cms\env\lib\site-packages\mongoengine\connection.py", l
   ine 143, in get_db
      source=conn_settings['authentication_source'])
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\database.py", line 89
   1, in authenticate
      self.connection._cache_credentials(self.name, credentials)
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\mongo_client.py", lin
   e 459, in _cache_credentials
      auth.authenticate(credentials, sock_info, self.__simple_command)
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\auth.py", line 243, i
   n authenticate
      auth_func(credentials[1:], sock_info, cmd_func)
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\auth.py", line 222, i
   n _authenticate_mongo_cr
      cmd_func(sock_info, source, query)
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\mongo_client.py", lin
   e 690, in __simple_command
      helpers._check_command_response(response, None, msg)
     File "E:\python\quokka-cms\env\lib\site-packages\pymongo\helpers.py", line 178
   , in _check_command_response
      raise OperationFailure(msg % errmsg, code, response)
   pymongo.errors.OperationFailure: command SON([('authenticate', 1), ('user', u'ro
   ot'), ('nonce', u'25a3725076e7af83'), ('key', u'd9a170092b5a4e3db5d9f81d8a886aee
   ')]) failed: auth failed

**Comment by rochacbruno** [comment]
Sorry I dont have a Windows machine to reproduce this error, can you try testing in a previous version of MongoDB?
