### ISSUE TITLE
Error on Change Password Form Submit (FlaskMail related)

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#262]
On Change Password FlaskMail is trying to send an email to the user (why?)

```
web_1   | Traceback (most recent call last):
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
web_1   |     return self.wsgi_app(environ, start_response)
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
web_1   |     response = self.make_response(self.handle_exception(e))
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
web_1   |     reraise(exc_type, exc_value, tb)
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
web_1   |     response = self.full_dispatch_request()
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
web_1   |     rv = self.handle_user_exception(e)
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
web_1   |     reraise(exc_type, exc_value, tb)
web_1   |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
web_1   |     rv = self.dispatch_request()
web_1   |   File "/usr/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
web_1   |     return view_func(**req.view_args)
web_1   |   File "/usr/lib/python2.7/cProfile.py", line 149, in runcall
web_1   |     return func(*args, **kw)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_login.py", line 663, in decorated_view
web_1   |     return func(*args, **kwargs)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_security/views.py", line 307, in change_password
web_1   |     change_user_password(current_user, form.new_password.data)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_security/changeable.py", line 44, in change_user_password
web_1   |     send_password_changed_notice(user)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_security/changeable.py", line 33, in send_password_changed_notice
web_1   |     send_mail(subject, user.email, 'change_notice', user=user)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_security/utils.py", line 333, in send_mail
web_1   |     mail.send(msg)
web_1   |   File "/usr/lib/python2.7/site-packages/flask_mail.py", line 491, in send
web_1   |     with self.connect() as connection:
web_1   |   File "/usr/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
web_1   |     self.host = self.configure_host()
web_1   |   File "/usr/lib/python2.7/site-packages/flask_mail.py", line 158, in configure_host
web_1   |     host = smtplib.SMTP(self.mail.server, self.mail.port)
web_1   |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
web_1   |     (code, msg) = self.connect(host, port)
web_1   |   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
web_1   |     self.sock = self._get_socket(host, port, self.timeout)
web_1   |   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
web_1   |     return socket.create_connection((host, port), timeout)
web_1   |   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
web_1   |     raise err
web_1   | error: [Errno 111] Connection refused
```

**Comment by ellisonleao** [comment]
Maybe a misconfiguration on the SMTP server? (haven't looked at the code though)

**Comment by rochacbruno** [comment]
Maybe, but why changing a password would send an email? I guess this is a
bug. On Flask Security only actions that needs mailing is recover password
and activation

Em sex, 17 de jul de 2015 13:24, Ellison Leão notifications@github.com
escreveu:

**Comment by rochacbruno** [comment]
Your were right @ellisonleao FlaskSecurity has included new features, one of them is sending email advice that password has changed.

Also it included "send me a link to login" very nice!
