### ISSUE TITLE
admin login error

### ISSUE THREAD

**Issue by superleemo** [quokkaproject/quokka#300]
I want to log in to admin, but there is an error.

[2015-09-15 12:04:42 +0000] [14508] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/werkzeug/wsgi.py", line 650, in **call**
    return app(environ, start_response)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, _args, *_kwargs)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, _args, *_kwargs)
  File "/home/superlimo/quokkacms/myquokka/quokka/core/admin/views.py", line 26, in index
    return self.render('admin/index.html')
  File "/home/superlimo/quokkacms/myquokka/quokka/core/admin/models.py", line 43, in render
    return render_template(template, theme=theme, *_kwargs)
  File "/home/superlimo/quokkacms/myquokka/quokka/core/templates.py", line 16, in render_template
    return render_theme_template(theme, template, *_context)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/quokka_themes/__init__.py", line 184, in render_theme_template
    return render_template('_themes/%s/%s' % (theme, last), **context)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superlimo/quokkacms/myquokka/quokka/themes/cosmo/templates/admin/index.html", line 1, in top-level template code
    {% extends theme('admin/master.html') %}
  File "/home/superlimo/quokkacms/myquokka/quokka/themes/cosmo/templates/admin/master.html", line 1, in top-level template code
    {% extends theme(admin_base_template) %}
  File "/home/superlimo/quokkacms/myquokka/quokka/themes/cosmo/templates/admin/base.html", line 22, in top-level template code
    {% block page_body %}
  File "/home/superlimo/quokkacms/myquokka/quokka/themes/cosmo/templates/admin/base.html", line 63, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/superlimo/quokkacms/myquokka/quokka/themes/cosmo/templates/admin/index.html", line 15, in block "body"
    <a class="btn btn-success btn-small" href="{{ url_for('postview.edit_view', id=post.id)}}">
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/home/superlimo/quokkacms/lib/python2.7/site-packages/werkzeug/routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('postview.edit_view', {'id': ObjectId('55f6bbb8a1234b2dfee3b3d3')}, None)

**Comment by rochacbruno** [comment]
The problem here is because you are using an old version of theme "cosmo"

BuildError: ('postview.edit_view', {'id': ObjectId('55f6bbb8a1234b2dfee3b3d3')}, None)

the above url changed from "postview.edit_view" to "post.edit_view" in the new Flask-Admin version

BuildError: ('post.edit_view', {'id': ObjectId('55f6bbb8a1234b2dfee3b3d3')}, None)

You have 2 options:
1. Fix the themes/cosmo changing all the urls.
2. Move to the new "pure"theme by changing your settings.py or local_settings.py

```
ADMIN_THEME = "admin"
DEFAULT_THEME = "pure"
```

Maybe, that values are also on your database, access mongo_db and chenge it there also if present.

```
python manage.py shell
```

Enters Ipython

```
from quokka.core.models import Config
settings = Config.objects(group='settings')
settings.values
```

Check if there is a template defined in your settings that is different from the new themes.
