### ISSUE TITLE
Whats the best way to upgrade?

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#306]
I see you have all poured a lot of hard work in this since I installed many months ago. (ps my site its running strong thanks!) Whats the best way to upgrade an existing installation?

**Comment by shaun10** [comment]
You can use git pull if you are on the master branch to get the latest production code running on your system/server. Then push the new code base to your host.

**Comment by eurabilis** [comment]
Ok great thanks!

**Comment by rochacbruno** [comment]
Hi, dont forget to update the packages installed in your Python Environment (virtualenv)

Use " pip install -r requirements/requirements.txt"  to upgrade.

If any problem, please recreate your env from scratch

**Comment by eurabilis** [comment]
Thanks Bruno I won't.

**Comment by eurabilis** [comment]
In trying to fix it  myself I bit the  bullet and made a new virtualenv and started over with the exception of my database and local_settings.py  file but I am still getting this error below in my quokka.log. Can someone help me make sense of this   please what am I missing here.

---

INFO in before_request [./quokka/ext/before_request.py:9]:

## Called only once, when the first request comes in

Traceback (most recent call last):
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 650, in **call**
    return app(environ, start_response)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(_args, *_kwargs)
  File "./quokka/core/views.py", line 144, in get
    channel=channel)
  File "./quokka/core/templates.py", line 16, in render_template
    return render_theme_template(theme, template, *_context)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/quokka_themes/**init**.py", line 191, in render_theme_templat
e
    return render_template(last, *_context)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: content/portal_list.html
[pid: 4000|app: 0|req: 1/1] 192.168.1.2 () {44 vars in 1167 bytes} [Sat Oct 10 18:34:44 2015] GET / => generated 0 bytes in 49
0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

**Comment by eurabilis** [comment]
I fixed it. Thanks anyway.

**Comment by zky001** [comment]
@eurabilis  how did you solve this problem?I want get help from your condition
