### ISSUE TITLE
google site tools unearthed some errors for me.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#318]
Good day ladies and gentlemen. While browsing google site tools it showed me there are several errors under the hood I never noticed. First, when trying to  access http://www.sid.dontexist.dynu.com/articles.xml I get a 502 bad gateway which just means there was an error with it. Here is what the log has to say immediately after accessing (or trying to access) `--------------------------------------------------------------------------------
INFO in before_request [./quokka/ext/before_request.py:9]:
## Called only once, when the first request comes in

Traceback (most recent call last):
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 650, in **call**
    return app(environ, start_response)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/home/quokka/quokkaenv/local/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request

```
return meth(*args, **kwargs)
```

  File "./quokka/core/views.py", line 529, in get
    return self.make_rss(feed_name, contents)
  File "./quokka/core/views.py", line 433, in make_rss
    content.title + content.get_absolute_url()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 17: ordinal not in range(128)
[pid: 2644|app: 0|req: 1/1] 192.168.1.2 () {46 vars in 1160 bytes} [Sat Nov 14 13:37:20 2015] GET /articles.xml => generated 0 bytes in 365 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
root@sid:/var/log/uwsgi/app#
`

Lasty I am getting a lot of 404 errors if I move categories around. Its as if google indexes me at a certain point and then if I change my articles or categories it goes back to find stuff and if it cant because its moved so it just gives a 404 rather then trying to find it. Is this normal? Im thinking it is and once I stop moving categories around (I like my stuff organized) it will index it one day and then be fine. Thanks for reading have a great day.

**Comment by rochacbruno** [comment]
Looks like unicode problem in content.title, it needs to have a unicode conversion.
