### ISSUE TITLE
AttributeError: 'BaseQuerySet' object has no attribute 'get_or_create'

### ISSUE THREAD

**Issue by timgogochen** [quokkaproject/quokka#337]
Hi supporter,

I follow guides, execute command "python manage.py accounts_createsuperuser" ,
program get error info like this:
###### ########################start

D:\python_source\quokka>python manage.py accounts_createsuperuser
No handlers could be found for logger "root"
Name: dsystem
Email: dsystem@163.com
Password:
Repeat for confirmation:
Traceback (most recent call last):
  File "manage.py", line 129, in <module>
    manager()
  File "C:\Python274\lib\site-packages\click\core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "C:\Python274\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Python274\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python274\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "C:\Python274\lib\site-packages\click\core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "D:\python_source\quokka\quokka\modules\accounts\commands\createsuperuser.py", line 14, in cli
    admin, created = Role.objects.get_or_create(name='admin')
AttributeError: 'BaseQuerySet' object has no attribute 'get_or_create'
###### #################################end

Could you help me solve this issue,
Thanks

**Comment by timgogochen** [comment]
upgrade packages to last version, cannot solve this issue,
pip install -r requirements/requirements.txt --upgrade

**Comment by rochacbruno** [comment]
The method get_or_create is in https://github.com/quokkaproject/flask-mongoengine/commit/3bb7b9693fe3561db5921957269cf9b7e79bebb3

of our fork of https://github.com/quokkaproject/flask-mongoengine

Can you please try to activate the env where quokka is running and do:

```
pip uninstall flask-mongoengine
# and then
pip install https://github.com/quokkaproject/flask-mongoengine/tarball/master
```

If works I will try to ensure this package on installation.

Thanks

**Comment by timgogochen** [comment]
Hi rochacbruno ，

It's does't work,
############
C:\python_source\quokka>python manage.py
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from quokka import create_app
  File "C:\python_source\quokka\quokka__init__.py", line 3, in <module>
    from quokka.core.admin import create_admin
  File "C:\python_source\quokka\quokka\core\admin__init__.py", line 8, in <mod
le>
    from quokka.core.models.subcontent import SubContentPurpose
  File "C:\python_source\quokka\quokka\core\models\subcontent.py", line 6, in <
odule>
    from quokka.core.db import db
  File "C:\python_source\quokka\quokka\core\db.py", line 4, in <module>
    from flask.ext.mongoengine import MongoEngine
  File "C:\Python274\lib\site-packages\flask\exthook.py", line 87, in load_modu
e
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.mongoengine
######################

Thanks

**Comment by timgogochen** [comment]
and after upgrade that, get new error info:
pip install https://github.com/quokkaproject/flask-mongoengine/tarball/master --upgrade
###################################
C:\python_source\quokka>python manage.py
No handlers could be found for logger "root"
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app()
  File "C:\python_source\quokka\quokka__init__.py", line 24, in create_app
    configure_extensions(app, admin_instance or admin)
  File "C:\python_source\quokka\quokka\ext__init__.py", line 25, in configure_e
xtensions
    blueprints.load_from_folder(app)
  File "C:\python_source\quokka\quokka\ext\blueprints.py", line 42, in load_from
_folder
    mods[fname] = importlib.import_module(module_name)
  File "C:\Python274\lib\importlib__init__.py", line 37, in import_module
    **import**(name)
  File "C:\python_source\quokka\quokka\modules\accounts\main.py", line 3, in <mo
dule>
    from .views import SwatchView, ProfileEditView, ProfileView
  File "C:\python_source\quokka\quokka\modules\accounts\views.py", line 37, in <
module>
    class ProfileEditView(MethodView):
  File "C:\python_source\quokka\quokka\modules\accounts\views.py", line 52, in P
rofileEditView
    'avatar_url',
  File "C:\Python274\lib\site-packages\flask_mongoengine\wtf\orm.py", line 275,
in model_form
    field_dict = model_fields(model, only, exclude, field_args, converter)
  File "C:\Python274\lib\site-packages\flask_mongoengine\wtf\orm.py", line 243,
in model_fields
    field = converter.convert(model, model_field, field_args.get(name))
  File "C:\Python274\lib\site-packages\flask_mongoengine\wtf\orm.py", line 49, i
n convert
    'description': field.help_text or '',
AttributeError: 'StringField' object has no attribute 'help_text'

#################################

Thanks

**Comment by timgogochen** [comment]
Hi rochacbruno 

I add function to flask_mongoengine/init.py. This issue solved,

class BaseQuerySet(QuerySet):
    """
    A base queryset with handy extras
    """

```
def get_or_404(self, *args, **kwargs):
    try:
        return self.get(*args, **kwargs)
    except (MultipleObjectsReturned, DoesNotExist, ValidationError):
        abort(404)

def first_or_404(self):

    obj = self.first()
    if obj is None:
        abort(404)

    return obj

def paginate(self, page, per_page, error_out=True):
    return Pagination(self, page, per_page)

def paginate_field(self, field_name, doc_id, page, per_page,
                   total=None):
    item = self.get(id=doc_id)
    count = getattr(item, field_name + "_count", '')
    total = total or count or len(getattr(item, field_name))
    return ListFieldPagination(self, doc_id, field_name, page, per_page,
                               total=total)

def get_or_create(self, write_options=None, auto_save=True,*q_objs, **query):
    defaults = query.get('defaults', {})
    if 'defaults' in query:
        del query['defaults']
    try:
        doc = self.get(*q_objs, **query)
        return doc, False
    except self._document.DoesNotExist:
        query.update(defaults)
        doc = self._document(**query)
        if auto_save:
            doc.save(write_options=write_options)
        return doc, True
```
