### ISSUE TITLE
'get_url' is undefined

### ISSUE THREAD

**Issue by timgogochen** [quokkaproject/quokka#339]
jinja2.exceptions.UndefinedError
UndefinedError: 'get_url' is undefined

Traceback (most recent call last)
File "C:\Python274\lib\site-packages\flask\app.py", line 1836, in **call**
return self.wsgi_app(environ, start_response)
File "C:\Python274\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python274\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python274\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python274\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python274\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Python274\lib\site-packages\flask_admin\base.py", line 68, in inner
return self._run_view(f, _args, *_kwargs)
File "C:\Python274\lib\site-packages\flask_admin\base.py", line 367, in _run_view
return fn(self, _args, *_kwargs)
File "C:\Python274\lib\site-packages\flask_admin\model\base.py", line 1814, in index_view
return_url=self._get_list_url(view_args),
File "C:\python_source\quokka\quokka\core\admin\models.py", line 43, in render
return render_template(template, theme=theme, *_kwargs)
File "C:\python_source\quokka\quokka\core\templates.py", line 16, in render_template
return render_theme_template(theme, template, *_context)
File "C:\Python274\lib\site-packages\quokka_themes__init__.py", line 191, in render_theme_template
return render_template(last, **context)
File "C:\Python274\lib\site-packages\flask\templating.py", line 128, in render_template
context, ctx.app)
File "C:\Python274\lib\site-packages\flask\templating.py", line 110, in _render
rv = template.render(context)
File "C:\Python274\lib\site-packages\jinja2\environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "C:\Python274\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 5, in top-level template code
{% import 'admin/actions.html' as actionlib with context %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\master.html", line 1, in top-level template code
{% extends admin_base_template %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 30, in top-level template code
{% block page_body %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 59, in block "page_body"
{% block body %}{% endblock %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 13, in block "body"
{% block model_menu_bar %}
File "C:\Python274\lib\site-packages\flask_admin\templates\bootstrap2\admin\model\list.html", line 24, in block "model_menu_bar"
<a href="{{ get_url('.create_view', url=return_url) }}" title="{{ _gettext('Create New Record') }}">{{ _gettext('Create') }}</a>
UndefinedError: 'get_url' is undefined

**Comment by rochacbruno** [comment]
Flask-Admin recently changed its templates and this function goes away. Quokka got updated, the version using the latest version of quokka is running in http://development.quokkaproject.org

I guess you are running an outdated version of the template files?

**Comment by rochacbruno** [comment]
Closing because the bug is un-re-producible
