### ISSUE TITLE
Error 500 while registering but account is created (because of missing SMTP config)

### ISSUE THREAD

**Issue by yeradis** [quokkaproject/quokka#40]
Thats the problem.

Here some log:

30.09 22:49:14 quokka       ERROR    Exception on /accounts/register [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_security/views.py", line 117, in register
    user = register_user(**form.to_dict())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    user=user, confirmation_link=confirmation_link)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_security/utils.py", line 260, in send_mail
    mail.send(msg)
  File "/Library/Python/2.7/site-packages/flask_mail.py", line 415, in send
    with self.connect() as connection:
  File "/Library/Python/2.7/site-packages/flask_mail.py", line 123, in **enter**
    self.host = self.configure_host()
  File "/Library/Python/2.7/site-packages/flask_mail.py", line 137, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 250, in **init**
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 310, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 285, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
30.09 22:49:14 werkzeug     INFO     127.0.0.1 - - [30/Sep/2013 22:49:14] "POST /accounts/register HTTP/1.1" 500 -

**Comment by rochacbruno** [comment]
well I am thiking on how to make the mail sending coditional to the presence of SMTP server settings.

**Comment by rochacbruno** [comment]
Fixed on flask-security configs.. to enable you should override configuration .
