### ISSUE TITLE
Installing problems with quokka

### ISSUE THREAD

**Issue by SPuerBRead** [quokkaproject/quokka#482]
when i use "manage accounts_createsuperuser"  
This error occurred

`Traceback (most recent call last):
  File "/usr/local/bin/manage", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/manage/cli.py", line 214, in main
    manager = init_cli(cli)
  File "/usr/local/lib/python2.7/dist-packages/manage/cli.py", line 204, in init_cli
    load_commands(cli, MANAGE_DICT)
  File "/usr/local/lib/python2.7/dist-packages/manage/commands_collector.py", line 90, in load_commands
    root_module = import_string(command_dict['module'])
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 49, in import_string
    module = import_string(module_name)
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 49, in import_string
    module = import_string(module_name)
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 61, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/import_string/base.py", line 36, in import_string
    __import__(import_name)
  File "./quokka/__init__.py", line 9, in <module>
    from quokka.core.admin import create_admin  # noqa
  File "./quokka/core/admin/__init__.py", line 7, in <module>
    from quokka.core.models.subcontent import SubContentPurpose
  File "./quokka/core/models/subcontent.py", line 6, in <module>
    from quokka.core.db import db
  File "./quokka/core/db.py", line 4, in <module>
    from flask_mongoengine import (
  File "/usr/local/lib/python2.7/dist-packages/flask_mongoengine/__init__.py", line 16, in <module>
    from mongoengine.base import ValidationError
import_string.base.ImportStringError: import_string() failed for 'quokka.core.commands'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportStringError: import_string() failed for 'quokka.core'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportStringError: import_string() failed for 'quokka'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'quokka' not found.

Original exception:

ImportError: cannot import name ValidationError`

Excuse me, is there something wrong with me?   thanks.

**Comment by marcosptf** [comment]
do you have install the requirements.* ?

execute:
pip freeze

if the quokka is not in the list, run pip install -r requirements again

:D

**Comment by SPuerBRead** [comment]
yes i use pip install -r requirements/requirements.txt ，error just said
and just now i use pip install quokka ，error becomes this

my english is not good -。- so there may be some places to express some of the problems.

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/manage", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/manage/cli.py", line 234, in main
    manager = init_cli(cli)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/manage/cli.py", line 224, in init_cli
    load_commands(cli, MANAGE_DICT)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/manage/commands_collector.py", line 90, in load_commands
    root_module = import_string(command_dict['module'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/import_string/base.py", line 36, in import_string
    __import__(import_name)
  File "./quokka/__init__.py", line 9, in <module>
    from quokka.core.admin import create_admin  # noqa
  File "./quokka/core/admin/__init__.py", line 7, in <module>
    from quokka.core.models.subcontent import SubContentPurpose
  File "./quokka/core/models/subcontent.py", line 6, in <module>
    from quokka.core.db import db
  File "./quokka/core/db.py", line 4, in <module>
    from flask_mongoengine import (
  File "/usr/local/lib/python2.7/dist-packages/flask_mongoengine/__init__.py", line 7, in <module>
    import mongoengine
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/__init__.py", line 3, in <module>
    from mongoengine import document
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 10, in <module>
    from mongoengine.base import (BaseDict, BaseDocument, BaseList,
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/__init__.py", line 9, in <module>
    from mongoengine.base.document import *
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 17, in <module>
    from mongoengine.base.fields import ComplexBaseField
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 474, in <module>
    class GeoJsonBaseField(BaseField):
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 480, in GeoJsonBaseField
    _geo_index = pymongo.GEOSPHERE
AttributeError: 'module' object has no attribute 'GEOSPHERE'

**Comment by yeyu456** [comment]
I met the same problem and I use mongodb 3.7.2. 
Try this, upgrade the flask-mongoengine version, it work for me.
`pip3 install --upgrade  Flask==0.12 flask-mongoengine=0.8.2  requests==2.13.0 manage==0.1.13 Pillow==4.0.0`

**Comment by likesubject** [comment]
I also encountered a similar problem, probably because the mongoengine package removed ValidationError at version 0.11.0, which is the official web change log (BREAKING CHANGE: from mongoengine.base import ErrorClass will not work anymore for any error from mongoengine.errors (eg ValidationError). Use from mongoengine.errors import ErrorClass instead. # 1428), while pip installs version 0.15.0 by default. I try to add mongoengine == 0.10.0 in requrements.txt to solve the problem.

**Comment by rochacbruno** [comment]
@likesubject quokka is now being rewritten in http://github.com/rochacbruno/quokka_ng and soon will move here.
