### ISSUE TITLE
Quick Start: 'make adduser' throwing exception

### ISSUE THREAD

**Issue by barrio** [quokkaproject/quokka#662]
I'm on Ubuntu Artful 64bit with Python 3.6. Going through the quick start section, after running 
`make adduser`
and confirming the password, the following exception is thrown:

Traceback (most recent call last):
  File "/home/barrios/code/quokka/venv/bin/quokka", line 10, in <module>
    sys.exit(main())
  File "/home/barrios/code/quokka/quokka/cli.py", line 192, in main
    return manager()
  File "/home/barrios/code/quokka/venv/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/barrios/code/quokka/venv/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/barrios/code/quokka/venv/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/barrios/code/quokka/venv/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/barrios/code/quokka/venv/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/barrios/code/quokka/quokka/cli.py", line 31, in decorator
    app = create_app(ENVMODE=kwargs.get('envmode'))
  File "/home/barrios/code/quokka/quokka/__init__.py", line 35, in create_app
    app = create_app_base(test=test, **settings)
  File "/home/barrios/code/quokka/quokka/__init__.py", line 18, in create_app_base
    configure_dynaconf(app)
  File "/home/barrios/code/quokka/quokka/core/flask_dynaconf.py", line 79, in configure_dynaconf
    filename=app.config.get('SETTINGS_MODULE')
TypeError: load() got an unexpected keyword argument 'namespace'

The test suite also doesn't run because of this error.

**Comment by rochacbruno** [comment]
#661 is going to fix that. My plan is to work on that and merge this weekend.

**Comment by josdyr** [comment]
I get the same error. Any progress, or any way around this? Cheers. Mac user here.

**Comment by zx9r** [comment]
I am also having this problem. How can we proceed before #661 is applyed ?

**Comment by rochacbruno** [comment]
done
