### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'theme' is undefined

### ISSUE THREAD

**Issue by jstacoder** [quokkaproject/quokka#663]
when i create a block or page, and try to view i get: 

```
2018-06-12 11:51:20,001 - werkzeug - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/quokka/core/error_handlers.py", line 54, in server_error_page
    return render_template("errors/server_error.html"), 500
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/kyle/git/blog/venv/lib/python3.6/site-packages/quokka/templates/errors/server_error.html", line 2, in top-level template code
    {% extends theme("base.html") %}
jinja2.exceptions.UndefinedError: 'theme' is undefined
```

**Comment by rochacbruno** [comment]
fixed
