### ISSUE TITLE
make adduser fail - AttributeError: module 'mistune' has no attribute 'Renderer'

### ISSUE THREAD

**Issue by Barceloch** [quokkaproject/quokka#687]
```
~/quokka$ make adduser
"Running quokka adduser..."
/home/barcelo/quokka/venv/lib/python3.6/site-packages/manage-0.1.13-py3.6.egg/manage/cli.py:44: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MANAGE_DICT.update(yaml.load(manage_file))
Username: ........
Fullname:......
Email: ........@gmail.com
Password: 
Repeat for confirmation: 
Traceback (most recent call last):
  File "/home/barcelo/quokka/venv/bin/quokka", line 10, in <module>
    sys.exit(main())
  File "/home/barcelo/quokka/quokka/cli.py", line 192, in main
    return manager()
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/barcelo/quokka/quokka/cli.py", line 31, in decorator
    app = create_app(ENVMODE=kwargs.get('envmode'))
  File "/home/barcelo/quokka/quokka/__init__.py", line 34, in create_app
    configure_extensions(app)
  File "/home/barcelo/quokka/quokka/core/__init__.py", line 22, in configure_extensions
    configure_extension(configurator_name, app=app, admin=admin)
  File "/home/barcelo/quokka/quokka/core/__init__.py", line 8, in configure_extension
    configurator = import_string(name)
  File "/home/barcelo/quokka/venv/lib/python3.6/site-packages/import_string-0.1.0-py3.6.egg/import_string/base.py", line 36, in import_string
    __import__(import_name)
  File "/home/barcelo/quokka/quokka/core/context_processors.py", line 1, in <module>
    from .content.models import make_model, Category
  File "/home/barcelo/quokka/quokka/core/content/__init__.py", line 2, in <module>
    from .admin import AdminArticlesView, AdminPagesView, AdminBlocksView
  File "/home/barcelo/quokka/quokka/core/content/admin.py", line 7, in <module>
    from quokka.admin.formatters import (
  File "/home/barcelo/quokka/quokka/admin/formatters.py", line 3, in <module>
    from quokka.core.content.models import make_model
  File "/home/barcelo/quokka/quokka/core/content/models.py", line 3, in <module>
    from .formats import get_format
  File "/home/barcelo/quokka/quokka/core/content/formats.py", line 4, in <module>
    from .parsers import markdown
  File "/home/barcelo/quokka/quokka/core/content/parsers.py", line 34, in <module>
    class HighlightRenderer(HighlightMixin, mistune.Renderer):
AttributeError: module 'mistune' has no attribute 'Renderer'
Makefile:56: recipe for target 'adduser' failed
make: *** [adduser] Error 1
```

**Comment by Barceloch** [comment]
solved with:
in /home/barcelo/quokka/quokka/core/content/parsers.py

```
class HighlightRenderer(HighlightMixin, mistune.HTMLRenderer):
    pass
    ...

markdown = mistune.create_markdown(renderer=HighlightRenderer())
```
