### ISSUE TITLE
Erro demo.quokkaproject.org

### ISSUE THREAD

**Issue by jniltinho** [quokkaproject/quokka#91]
```
warning: no files found matching '*.pot' under directory 'pytz'
warning: no previously-included files found matching 'test_zdump.py'
```

Successfully installed flask flask-script WTForms mongoengine flask-mongoengine blinker Flask-Assets Flask-Babel Flask-Bcrypt Flask-Misaka Flask-Gravatar Flask-Login Flask-Principal Flask-Mail Flask-Testing Flask-Cache flask-debugtoolbar dealer flask-collect flake8 passlib twill markupsafe Pillow pyyaml speaklater Flask-WTF itsdangerous Flask-Security Flask-HTMLBuilder Flask-Admin Babel Jinja2 Flask-BabelEx simplejson Quokka-Themes Werkzeug pymongo webassets py-bcrypt misaka pyflakes pep8 mccabe pytz
Cleaning up...
Loading fixtures
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    app = create_app()
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/**init**.py", line 44, in create_app
    configure_extensions(app, admin_instance or admin)
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/ext/**init**.py", line 30, in configure_extensions
    fixtures.configure(app, db)
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/ext/fixtures.py", line 17, in configure
    populate.create_configs()
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/utils/populate.py", line 170, in create_configs
    self.create_config(config)
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/utils/populate.py", line 92, in create_config
    return Config.objects.create(**data)
  File "/var/www/demo.quokkaproject.org/web/quokka-env/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 201, in create
    return self._document(**kwargs).save()
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/core/models.py", line 406, in save
    super(Config, self).save(_args, *_kwargs)
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/core/models.py", line 50, in save
    user = get_current_user()
  File "/var/www/clients/client1/web5/web/quokka-env/quokka/quokka/utils/**init**.py", line 19, in get_current_user
    if not current_user.is_authenticated():
  File "/var/www/demo.quokkaproject.org/web/quokka-env/local/lib/python2.7/site-packages/werkzeug/local.py", line 338, in **getattr**
    return getattr(self._get_current_object(), name)
  File "/var/www/demo.quokkaproject.org/web/quokka-env/local/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/var/www/demo.quokkaproject.org/web/quokka-env/local/lib/python2.7/site-packages/flask_login.py", line 47, in <lambda>
    current_app.login_manager.anonymous_user())
  File "/var/www/demo.quokkaproject.org/web/quokka-env/local/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'QuokkaApp' object has no attribute 'login_manager'

**Comment by rochacbruno** [comment]
Fixed!
